// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package index

import (
	"github.com/crazyfrankie/voidx/internal/core/embedding"
	"github.com/crazyfrankie/voidx/internal/core/file_extractor"
	"github.com/crazyfrankie/voidx/internal/core/retrievers"
	"github.com/crazyfrankie/voidx/internal/index/repository"
	"github.com/crazyfrankie/voidx/internal/index/repository/dao"
	service3 "github.com/crazyfrankie/voidx/internal/index/service"
	"github.com/crazyfrankie/voidx/internal/process_rule/service"
	service2 "github.com/crazyfrankie/voidx/internal/retriever/service"
	"github.com/crazyfrankie/voidx/internal/vecstore"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitIndexModule(db *gorm.DB, cmd redis.Cmdable, fileExtractor *file_extractor.FileExtractor, embeddingsSvc *embedding.EmbeddingService, jiebaService *retrievers.JiebaService, processRuleService *service.ProcessRuleService, keywordSvc *service2.KeywordService, vectorDatabaseService *vecstore.VecStoreService) *IndexModule {
	indexingDao := dao.NewIndexingDao(db)
	indexingRepo := repository.NewIndexingRepo(indexingDao)
	indexingService := service3.NewIndexingService(indexingRepo, cmd, fileExtractor, processRuleService, embeddingsSvc, jiebaService, keywordSvc, vectorDatabaseService)
	indexModule := &IndexModule{
		Service: indexingService,
	}
	return indexModule
}

// wire.go:

type Service = service3.IndexingService

type IndexModule struct {
	Service *Service
}
