// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package platform

import (
	"github.com/crazyfrankie/voidx/internal/platform/handler"
	"github.com/crazyfrankie/voidx/internal/platform/repository"
	"github.com/crazyfrankie/voidx/internal/platform/repository/dao"
	"github.com/crazyfrankie/voidx/internal/platform/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitPlatformModule(db *gorm.DB) *PlatformModule {
	platformDao := dao.NewPlatformDao(db)
	platformRepo := repository.NewPlatformRepo(platformDao)
	platformService := service.NewPlatformService(platformRepo)
	platformHandler := handler.NewPlatformHandler(platformService)
	platformModule := &PlatformModule{
		Handler: platformHandler,
	}
	return platformModule
}

// wire.go:

type Handler = handler.PlatformHandler

type PlatformModule struct {
	Handler *Handler
}

var ProviderSet = wire.NewSet(dao.NewPlatformDao, repository.NewPlatformRepo, service.NewPlatformService, handler.NewPlatformHandler)
