// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package assistant_agent

import (
	"context"
	"github.com/crazyfrankie/voidx/conf"
	"github.com/crazyfrankie/voidx/internal/assistant_agent/handler"
	"github.com/crazyfrankie/voidx/internal/assistant_agent/repository"
	"github.com/crazyfrankie/voidx/internal/assistant_agent/repository/dao"
	"github.com/crazyfrankie/voidx/internal/assistant_agent/service"
	"github.com/crazyfrankie/voidx/internal/assistant_agent/task"
	"github.com/crazyfrankie/voidx/internal/conversation"
	"github.com/crazyfrankie/voidx/internal/core/agent"
	"github.com/crazyfrankie/voidx/internal/core/llm"
	"github.com/crazyfrankie/voidx/internal/core/llm/entities"
	"github.com/crazyfrankie/voidx/internal/core/memory"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAssistantModule(db *gorm.DB, conversationSvc *conversation.ConversationModule, agentManager *agent.AgentQueueManagerFactory, llmManager *llm.LanguageModelManager, tokeBufMem *memory.TokenBufferMemory) *AssistantModule {
	assistantAgentDao := dao.NewAssistantAgentDao(db)
	assistantAgentRepo := repository.NewAssistantAgentRepo(assistantAgentDao)
	conversationService := conversationSvc.Service
	appProducer := InitProducer()
	baseLanguageModel := InitModel(llmManager)
	assistantAgentService := service.NewAssistantAgentService(assistantAgentRepo, conversationService, appProducer, llmManager, tokeBufMem, agentManager, baseLanguageModel)
	assistantAgentHandler := handler.NewAssistantAgentHandler(assistantAgentService)
	assistantModule := &AssistantModule{
		Handler: assistantAgentHandler,
	}
	return assistantModule
}

// wire.go:

type Handler = handler.AssistantAgentHandler

type AssistantModule struct {
	Handler *Handler
}

var ProviderSet = wire.NewSet(dao.NewAssistantAgentDao, repository.NewAssistantAgentRepo, service.NewAssistantAgentService, handler.NewAssistantAgentHandler)

func InitModel(llmManager *llm.LanguageModelManager) entities.BaseLanguageModel {
	model, err := llmManager.CreateModel(context.Background(), "tongyi", "qwen-max", map[string]any{
		"base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
	})
	if err != nil {
		panic(err)
	}

	return model
}

func InitProducer() *task.AppProducer {
	producer, err := task.NewAppProducer(conf.GetConf().Kafka.Brokers)
	if err != nil {
		panic(err)
	}

	return producer
}
