// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package process_rule

import (
	"github.com/crazyfrankie/voidx/internal/process_rule/repository"
	"github.com/crazyfrankie/voidx/internal/process_rule/repository/dao"
	"github.com/crazyfrankie/voidx/internal/process_rule/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitProcessRuleModule(db *gorm.DB) *ProcessRuleModule {
	processRuleDao := dao.NewProcessRuleDao(db)
	processRuleRepo := repository.NewProcessRuleRepo(processRuleDao)
	processRuleService := service.NewProcessRuleService(processRuleRepo)
	processRuleModule := &ProcessRuleModule{
		Service: processRuleService,
	}
	return processRuleModule
}

// wire.go:

type Service = service.ProcessRuleService

type ProcessRuleModule struct {
	Service *Service
}
