// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package upload

import (
	"github.com/crazyfrankie/voidx/internal/upload/handler"
	"github.com/crazyfrankie/voidx/internal/upload/repository"
	"github.com/crazyfrankie/voidx/internal/upload/repository/dao"
	"github.com/crazyfrankie/voidx/internal/upload/service"
	"github.com/google/wire"
	"github.com/minio/minio-go/v7"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUploadModule(db *gorm.DB, minioCli *minio.Client) *UploadModule {
	uploadFileDao := dao.NewUploadFileDao(db)
	uploadFileRepo := repository.NewUploadFileRepo(uploadFileDao)
	uploadFileService := service.NewUploadFileService(uploadFileRepo, minioCli)
	uploadFileHandler := handler.NewUploadFileHandler(uploadFileService)
	uploadModule := &UploadModule{
		Handler: uploadFileHandler,
	}
	return uploadModule
}

// wire.go:

type Handler = handler.UploadFileHandler

type UploadModule struct {
	Handler *Handler
}

var ProviderSet = wire.NewSet(dao.NewUploadFileDao, repository.NewUploadFileRepo, service.NewUploadFileService, handler.NewUploadFileHandler)
