// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package upload

import (
	"github.com/crazyfrankie/voidx/infra/contract/storage"
	"github.com/crazyfrankie/voidx/internal/upload/handler"
	"github.com/crazyfrankie/voidx/internal/upload/repository"
	"github.com/crazyfrankie/voidx/internal/upload/repository/dao"
	"github.com/crazyfrankie/voidx/internal/upload/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUploadModule(db *gorm.DB, minioCli storage.Storage) *UploadModule {
	uploadFileDao := dao.NewUploadFileDao(db)
	uploadFileRepo := repository.NewUploadFileRepo(uploadFileDao)
	ossService := service.NewOssService(uploadFileRepo, minioCli)
	uploadFileHandler := handler.NewUploadFileHandler(ossService)
	uploadModule := &UploadModule{
		Handler: uploadFileHandler,
		Service: ossService,
	}
	return uploadModule
}

// wire.go:

type Handler = handler.UploadFileHandler

type Service = service.OssService

type UploadModule struct {
	Handler *Handler
	Service *Service
}

var ProviderSet = wire.NewSet(dao.NewUploadFileDao, repository.NewUploadFileRepo, service.NewOssService, handler.NewUploadFileHandler)
