// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/voidx/internal/controller"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitEngine() *gin.Engine {
	chatHandler := controller.NewChatHandler()
	engine := InitWeb(chatHandler)
	return engine
}
