// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/voidx/internal/account"
	"github.com/crazyfrankie/voidx/internal/app"
	"github.com/crazyfrankie/voidx/internal/auth"
	"github.com/crazyfrankie/voidx/internal/llm"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitEngine() *gin.Engine {
	cmdable := InitCache()
	tokenService := InitJWT(cmdable)
	v := InitMiddlewares(tokenService)
	db := InitDB()
	languageModelManager := InitLLMCore()
	llmModule := llm.InitLLMModule(languageModelManager)
	appModule := app.InitAppModule(db, languageModelManager, llmModule)
	appHandler := appModule.Handler
	authModule := auth.InitAuthModule(db, cmdable, tokenService)
	authHandler := authModule.Handler
	accountModule := account.InitAccountModule(db)
	accountHandler := accountModule.Handler
	llmHandler := llmModule.Handler
	engine := InitWeb(v, appHandler, authHandler, accountHandler, llmHandler)
	return engine
}

// wire.go:

var BaseSet = wire.NewSet(InitCache, InitDB, InitLLMCore, InitJWT)
