// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/voidx/internal/controller"
	"github.com/crazyfrankie/voidx/internal/repository/dao"
	"github.com/crazyfrankie/voidx/internal/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitEngine() *gin.Engine {
	v := InitMiddlewares()
	db := InitDB()
	chatDao := dao.NewChatDao(db)
	chatService := service.NewChatService(chatDao)
	chatHandler := controller.NewChatHandler(chatService)
	engine := InitWeb(v, chatHandler)
	return engine
}
