// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/crazyfrankie/voidx/internal/app/handler"
	"github.com/crazyfrankie/voidx/internal/app/repository"
	"github.com/crazyfrankie/voidx/internal/app/repository/dao"
	"github.com/crazyfrankie/voidx/internal/app/service"
	"github.com/crazyfrankie/voidx/internal/core/llm"
	"github.com/crazyfrankie/voidx/internal/core/llm/entity"
	"github.com/crazyfrankie/voidx/internal/vecstore"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAppModule(db *gorm.DB, vecStore *vecstore.VecStoreService, llmCore *llm.LanguageModelManager) *AppModule {
	appDao := dao.NewAppDao(db)
	appRepo := repository.NewAppRepo(appDao)
	baseLanguageModel := InitModel(llmCore)
	appService := service.NewAppService(appRepo, vecStore, baseLanguageModel)
	appHandler := handler.NewAppHandler(appService)
	appModule := &AppModule{
		Handler: appHandler,
		Service: appService,
	}
	return appModule
}

// wire.go:

type Handler = handler.AppHandler

type Service = service.AppService

type AppModule struct {
	Handler *Handler
	Service *Service
}

func InitModel(llmManager *llm.LanguageModelManager) entity.BaseLanguageModel {
	model, err := llmManager.CreateModel("tongyi", "qwen-max", map[string]any{
		"base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
	})
	if err != nil {
		panic(err)
	}

	return model
}
