// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package oauth

import (
	"github.com/crazyfrankie/voidx/internal/oauth/handler"
	"github.com/crazyfrankie/voidx/internal/oauth/repository"
	"github.com/crazyfrankie/voidx/internal/oauth/repository/dao"
	"github.com/crazyfrankie/voidx/internal/oauth/service"
	"github.com/crazyfrankie/voidx/pkg/jwt"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitOAuthModule(db *gorm.DB, token *jwt.TokenService) *OAuthModule {
	oAuthDao := dao.NewOAuthDao(db)
	oAuthRepo := repository.NewOAuthRepo(oAuthDao)
	oAuthService := service.NewOAuthService(oAuthRepo, token)
	oAuthHandler := handler.NewOAuthHandler(oAuthService)
	oAuthModule := &OAuthModule{
		Handler: oAuthHandler,
	}
	return oAuthModule
}

// wire.go:

type Handler = handler.OAuthHandler

type OAuthModule struct {
	Handler *Handler
}
