// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package account

import (
	"github.com/crazyfrankie/voidx/internal/account/handler"
	"github.com/crazyfrankie/voidx/internal/account/repository"
	"github.com/crazyfrankie/voidx/internal/account/repository/dao"
	"github.com/crazyfrankie/voidx/internal/account/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAccountModule(db *gorm.DB) *AccountModule {
	accountDao := dao.NewAccountDao(db)
	accountRepo := repository.NewAccountRepo(accountDao)
	accountService := service.NewAccountService(accountRepo)
	accountHandler := handler.NewAccountHandler(accountService)
	accountModule := &AccountModule{
		Handler: accountHandler,
	}
	return accountModule
}

// wire.go:

type Handler = handler.AccountHandler

type AccountModule struct {
	Handler *Handler
}
