// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package builtin_tools

import (
	"github.com/crazyfrankie/voidx/internal/builtin_tools/handler"
	"github.com/crazyfrankie/voidx/internal/builtin_tools/service"
	"github.com/crazyfrankie/voidx/internal/core/tools/builtin_tools/categories"
	"github.com/crazyfrankie/voidx/internal/core/tools/builtin_tools/providers"
)

// Injectors from wire.go:

func InitBuiltinToolsModule(toolManager *categories.BuiltinCategoryManager, providerManager *providers.BuiltinProviderManager) *BuiltinToolsModule {
	builtinToolsService := service.NewBuiltinToolsService(toolManager, providerManager)
	builtinToolsHandler := handler.NewBuiltinToolsHandler(builtinToolsService)
	builtinToolsModule := &BuiltinToolsModule{
		Handler: builtinToolsHandler,
	}
	return builtinToolsModule
}

// wire.go:

type Handler = handler.BuiltinToolsHandler

type BuiltinToolsModule struct {
	Handler *Handler
}
