// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ai

import (
	"github.com/crazyfrankie/voidx/internal/ai/handler"
	"github.com/crazyfrankie/voidx/internal/ai/repository"
	"github.com/crazyfrankie/voidx/internal/ai/repository/dao"
	"github.com/crazyfrankie/voidx/internal/ai/service"
	"github.com/crazyfrankie/voidx/internal/conversation"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAIModule(db *gorm.DB, conversationModule *conversation.ConversationModule) *AIModule {
	aiDao := dao.NewAIDao(db)
	aiRepo := repository.NewAIRepo(aiDao)
	conversationService := conversationModule.Service
	aiService := service.NewAIService(aiRepo, conversationService)
	aiHandler := handler.NewAIHandler(aiService)
	aiModule := &AIModule{
		Handler: aiHandler,
	}
	return aiModule
}

// wire.go:

type Handler = handler.AIHandler

type AIModule struct {
	Handler *Handler
}

var ProviderSet = wire.NewSet(dao.NewAIDao, repository.NewAIRepo, service.NewAIService, handler.NewAIHandler)
