// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package audio

import (
	"github.com/crazyfrankie/voidx/internal/audio/handler"
	"github.com/crazyfrankie/voidx/internal/audio/repository"
	"github.com/crazyfrankie/voidx/internal/audio/repository/dao"
	"github.com/crazyfrankie/voidx/internal/audio/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAudioModule(db *gorm.DB) *AudioModule {
	audioDao := dao.NewAudioDao(db)
	audioRepo := repository.NewAudioRepo(audioDao)
	audioService := service.NewAudioService(audioRepo)
	audioHandler := handler.NewAudioHandler(audioService)
	audioModule := &AudioModule{
		Handler: audioHandler,
	}
	return audioModule
}

// wire.go:

type Handler = handler.AudioHandler

type AudioModule struct {
	Handler *Handler
}

var ProviderSet = wire.NewSet(dao.NewAudioDao, repository.NewAudioRepo, service.NewAudioService, handler.NewAudioHandler)
