// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api_key

import (
	"github.com/crazyfrankie/voidx/internal/api_key/handler"
	"github.com/crazyfrankie/voidx/internal/api_key/repository"
	"github.com/crazyfrankie/voidx/internal/api_key/repository/dao"
	"github.com/crazyfrankie/voidx/internal/api_key/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitApiKeyModule(db *gorm.DB) *ApiKeyModule {
	apiKeyDao := dao.NewApiKeyDao(db)
	apiKeyRepo := repository.NewApiKeyRepo(apiKeyDao)
	apiKeyService := service.NewApiKeyService(apiKeyRepo)
	apiKeyHandler := handler.NewApiKeyHandler(apiKeyService)
	apiKeyModule := &ApiKeyModule{
		Handler: apiKeyHandler,
	}
	return apiKeyModule
}

// wire.go:

type Handler = handler.ApiKeyHandler

type ApiKeyModule struct {
	Handler *Handler
}

var ProviderSet = wire.NewSet(dao.NewApiKeyDao, repository.NewApiKeyRepo, service.NewApiKeyService, handler.NewApiKeyHandler)
