// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/crazyfrankie/voidx/internal/auth/handler"
	"github.com/crazyfrankie/voidx/internal/auth/repository"
	"github.com/crazyfrankie/voidx/internal/auth/repository/dao"
	"github.com/crazyfrankie/voidx/internal/auth/service"
	"github.com/crazyfrankie/voidx/pkg/jwt"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAuthModule(db *gorm.DB, cmd redis.Cmdable, token *jwt.TokenService) *AuthModule {
	authDao := dao.NewAuthDao(db)
	authRepo := repository.NewAuthRepo(authDao)
	authService := service.NewAuthService(authRepo, token)
	authHandler := handler.NewAuthHandler(authService)
	authModule := &AuthModule{
		Handler: authHandler,
	}
	return authModule
}

// wire.go:

type Handler = handler.AuthHandler

type AuthModule struct {
	Handler *Handler
}
