// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apitool

import (
	"github.com/crazyfrankie/voidx/internal/apitool/handler"
	"github.com/crazyfrankie/voidx/internal/apitool/repository"
	"github.com/crazyfrankie/voidx/internal/apitool/repository/dao"
	"github.com/crazyfrankie/voidx/internal/apitool/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitApiToolHandler(db *gorm.DB) *ApiToolModule {
	apiToolDao := dao.NewApiToolDao(db)
	apiToolRepo := repository.NewApiToolRepo(apiToolDao)
	apiToolService := service.NewApiToolService(apiToolRepo)
	apiToolHandler := handler.NewApiToolHandler(apiToolService)
	apiToolModule := &ApiToolModule{
		Handler: apiToolHandler,
	}
	return apiToolModule
}

// wire.go:

type Handler = handler.ApiToolHandler

type ApiToolModule struct {
	Handler *Handler
}

var ApiToolSet = wire.NewSet(dao.NewApiToolDao, repository.NewApiToolRepo, service.NewApiToolService, handler.NewApiToolHandler)
