// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package llm

import (
	"github.com/crazyfrankie/voidx/internal/core/llm"
	"github.com/crazyfrankie/voidx/internal/llm/handler"
	"github.com/crazyfrankie/voidx/internal/llm/service"
)

// Injectors from wire.go:

func InitLLMModule(llmCore *llm.LanguageModelManager) *LLMModule {
	llmService := service.NewLLMService(llmCore)
	llmHandler := handler.NewLLMHandler(llmService)
	llmModule := &LLMModule{
		Handler: llmHandler,
		Service: llmService,
	}
	return llmModule
}

// wire.go:

type Handler = handler.LLMHandler

type Service = service.LLMService

type LLMModule struct {
	Handler *Handler
	Service *Service
}
