// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package analysis

import (
	"github.com/crazyfrankie/voidx/internal/analysis/handler"
	"github.com/crazyfrankie/voidx/internal/analysis/repository"
	"github.com/crazyfrankie/voidx/internal/analysis/repository/cache"
	"github.com/crazyfrankie/voidx/internal/analysis/repository/dao"
	"github.com/crazyfrankie/voidx/internal/analysis/service"
	"github.com/crazyfrankie/voidx/internal/app"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAnalysisModule(db *gorm.DB, rdb redis.Cmdable, appModule *app.AppModule) *AnalysisModule {
	analysisDao := dao.NewAnalysisDao(db)
	analysisCache := cache.NewAnalysisCache(rdb)
	analysisRepo := repository.NewAnalysisRepo(analysisDao, analysisCache)
	appService := appModule.Service
	analysisService := service.NewAnalysisService(analysisRepo, appService)
	analysisHandler := handler.NewAnalysisHandler(analysisService)
	analysisModule := &AnalysisModule{
		Handler: analysisHandler,
	}
	return analysisModule
}

// wire.go:

type Handler = handler.AnalysisHandler

type AnalysisModule struct {
	Handler *Handler
}

var ProviderSet = wire.NewSet(dao.NewAnalysisDao, cache.NewAnalysisCache, repository.NewAnalysisRepo, service.NewAnalysisService, handler.NewAnalysisHandler)
