// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package builtin_app

import (
	"github.com/crazyfrankie/voidx/internal/builtin_app/handler"
	"github.com/crazyfrankie/voidx/internal/builtin_app/repository"
	"github.com/crazyfrankie/voidx/internal/builtin_app/repository/dao"
	"github.com/crazyfrankie/voidx/internal/builtin_app/service"
	"github.com/crazyfrankie/voidx/internal/core/builtin_apps"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitBuiltinAppModule(db *gorm.DB, builtinManager *builtin_apps.BuiltinAppManager) *BuiltinModule {
	builtinDao := dao.NewBuiltinDao(db)
	builtinRepository := repository.NewBuiltinRepository(builtinDao)
	builtinService := service.NewBuiltinService(builtinRepository, builtinManager)
	builtinAppHandler := handler.NewBuiltinAppHandler(builtinService)
	builtinModule := &BuiltinModule{
		Handler: builtinAppHandler,
	}
	return builtinModule
}

// wire.go:

type Handler = handler.BuiltinAppHandler

type BuiltinModule struct {
	Handler *Handler
}
